[build]
  publish = "dist"
  command = "pnpm install --no-frozen-lockfile && pnpm build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 3000
  publish = "dist"