[build]
  publish = "dist"
  command = "corepack enable && pnpm install --frozen-lockfile=false && pnpm build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200