[build]
  publish = "dist"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-frozen-lockfile"
  NETLIFY_USE_PNPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 3000
  publish = "dist"